'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('UserLikedStories', [
        {userId: 1, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 2, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 3, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 4, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 5, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 6, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 7, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 8, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 9, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 10, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 11, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 12, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 13, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 14, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 15, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 16, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 17, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 18, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 19, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 20, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 21, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 22, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 23, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 24, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 25, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 26, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 27, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 28, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 29, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 30, storyId: 1, createdAt: new Date(), updatedAt: new Date()},
        {userId: 1, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 2, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 3, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 4, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 5, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 6, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 7, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 8, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 9, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 10, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 11, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 12, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 13, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 14, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 15, storyId: 2, createdAt: new Date(), updatedAt: new Date()},
        {userId: 1, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 2, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 3, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 4, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 5, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 6, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 7, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 8, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 9, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 10, storyId: 3, createdAt: new Date(), updatedAt: new Date()},
        {userId: 1, storyId: 4, createdAt: new Date(), updatedAt: new Date()},
        {userId: 2, storyId: 4, createdAt: new Date(), updatedAt: new Date()},
        {userId: 3, storyId: 4, createdAt: new Date(), updatedAt: new Date()},
        {userId: 4, storyId: 4, createdAt: new Date(), updatedAt: new Date()},
        {userId: 5, storyId: 4, createdAt: new Date(), updatedAt: new Date()},
      ], {});
    
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('UserLikedStories', null, {});
    
  }
};
